### ISSUE TITLE
增加 PTT passwd 檔案其他欄位的解析

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/go-bbs#1]
預定修改的程式碼為

passwd.go

passwd_test.go

兩個檔案，請參考 https://github.com/ptt/pttbbs/blob/master/include/pttstruct.h 裡面的 userec 結構將 testcase 裡面的 passwd 檔案的內容解出來並做成測試檔。

**Comment by chhsiao1981** [comment]
#8 intended to resolve this issue, but #8 is too large.

Will break #8 with the following sub-pr:

1. ptttype as the most fundamental types.
2. cmbbs as the lib.
3. ptt as the top-most functions.

**Comment by chhsiao1981** [comment]
Programming convention:

1. accessing raw data through big5-fixed-length-bytes struct first (easily deserialize through binary.Read)
2. converting big5-fixed-length-bytes struct to utf8-string struct for further processing.
3. The Function-naming should be as much the same as the original pttbbs repo, unless there is a better coding-style in go. (cmbbs/names.c/is_invaliduser => cmbbs/names.go/IsInvalidUser
4. const / config-variables (#define) is in ptttypes/const.go or ptttypes/config.go
5. Avoid using c code unless necessary (shm / crypt). Wrap the c code as the separated module (to be easily replaced in the future.)

**Comment by PichuChen** [comment]
他修改的檔案數量雖然分成三個PR了，但是還是有到六十幾個

**Comment by PichuChen** [comment]
如果一週後沒有其他問題的話就關閉這個 ISSUE 吧～

**Comment by chhsiao1981** [comment]
cmbbs and mbbsd requires shm.
(for user-hash-table)

It's extremely hard to get rid of ptt-code in shm.
(shm is a pointer pointing to the shared-mem, and use the C-feature to automatically mapped to the SHM_t structure,
 golang is GC-based and can not automatically map the data to type SHM struct)

It's possible that we have our own shared-mem mechanism AFTER ptt-c-code is retired.
We do need ptt-c-code for shm before ptt-c-code is retired.

**Comment by PichuChen** [comment]
目前在劣文數量以及五子棋象棋等的資料還沒有被Parse出來 (PTT部分)

**Comment by titaneric** [comment]
Hi,
我可以嘗試parsing剩餘的資料，目前已有將PASSWD其他欄位對過C以及Go

**Comment by PichuChen** [comment]
> Hi,
> 我可以嘗試parsing剩餘的資料，目前已有將PASSWD其他欄位對過C以及Go

OK，那你那邊是打算一口氣把剩下的都做完嗎？ 還是先開一個子 ISSUE 把某個範圍的做完？

**Comment by titaneric** [comment]
我可能先開子issue把遊戲成績補齊之後再把其他補完

**Comment by PichuChen** [comment]
> 我可能先開子issue把遊戲成績補齊之後再把其他補完

你好像變成直接送 PR 而不是另外開立子 ISSUE 了喔

**Comment by titaneric** [comment]
看到PR被merge進來了，感恩。
請問還有欄位需要補嗎？看起來這個issue已經解掉了
