### ISSUE TITLE
gRPC server (or web-server) to communicate with python-server

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/go-bbs#12]
The login-feature is almost done～
We are able to start setting-up the service to communicate with python-server.

Based on the information that I obtained:

1. Will use gPRC to communicate between each other.
2. Use jwt to send the user-info to python-server.
3. python-server is responsible for recording the jwt-info (user-info) in its own db.

**Comment by PichuChen** [comment]
剛開始我的想法是不會使用 gRPC 進行，因為如果要用 gRPC 開發的話文件需要再補上 protobuf 環境的安裝方式。

一開始還是會先考慮用傳統的 RESTFul + JSON 的方式進行

然後登入以及取文章等等的 API Path 可以開始討論了

**Comment by chhsiao1981** [comment]
We need crypt (passwd-hash) and shm (user-id hash-table) to do login before we can do api-server

**Comment by PichuChen** [comment]
補個 crypt #13 的連結。

**Comment by PichuChen** [comment]
API Server 的實作方式我的想法是會另外增加一個package (子資料夾) 可能叫做 serverlet 或者是 bbsd 之類的，然後他編譯成可執行檔去使用 go-bbs 這個套件內的東西
