### ISSUE TITLE
fav-info is stored in in-process mem.

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/go-bbs#20]
Found that fav-info is stored in in-process mem,
and is brutal-forcely do fav-save when the ssh/telnet/ws session is done.

https://github.com/ptt/pttbbs/blob/master/mbbsd/board.c#L1647
https://github.com/ptt/pttbbs/blob/master/mbbsd/mbbsd.c#L206

Design concern:
1. At least the fav-info in-file should be with one complete version. it shouldn't be parts from one connection and the others from another connection (resulting broken file)
2. We should request the fav-info from file as least as possible.
3. fav-info is a many-reads-few-writes operation.

Currently pttbbs allows at most 3 concurrent connections. So it's ok to have possible conflicting fav-setup as long as we stick to Design 1.
(In rare situation, the user has a dead process, and the user allows the dead process continue working,
 and the user modify the fav-info and logout before the dead-process is killed.)
(The user will just reset it again)

Requires frontend to take care of fav-editing and middleware to have cache of the fav-info.

When doing get-fav from frontend-UI:
1. middleware check the cache first.
2. if the cache is within n seconds (10 for now). return the cache.
3. middleware provides last-load-time with the go-bbs and try to get the fav from file.
4. go-bbs: first compare the load-time with the mtime of the file. return mtime as no-need to update. otherwise return the full fav.
5. middleware update the cache accordingly.

When doing update-fav from frontend-UI:
1. frontend takes care of the editing, do only fav-save to the middleware. (frontend shouldn't do fav-save within 10 seconds.)
2. the middleware store in tmp-db, spawn process/thread to do fav-save after 10 second.
3. the middleware check that the fav-save is still the newest setup to do. do save on go-bbs.
4. go-bbs do fav-save only when the load-time from the middleware is newer than the mtime. return fav-from-file to middleware to ensure sync from fav-from-file.

**Comment by chhsiao1981** [comment]
long-term TODO: pttbbs use db to save .FAV, to avoid continuous-querying-file from go-bbs.

**Comment by PichuChen** [comment]
目前應該從靜態檔案讀取我的最愛的部分也還沒實作？

**Comment by chhsiao1981** [comment]
It is in the process of development.

https://github.com/chhsiao1981/go-bbs/tree/dev/fav
