### ISSUE TITLE
使用者修改密碼後，API 端並不會即時更新新的使用者密碼

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/go-bbs#23]
如題，因為目前載入密碼檔案的機制是在程式執行時進行的。

也許要把它改成每次驗證時重新載入？或是幾分鐘重新載入？或是有什麼機制讓他重新載入這樣。

**Comment by PichuChen** [comment]
如果說知道是 Linux 的話，那使用 inotify 如何？

**Comment by PichuChen** [comment]
https://github.com/fsnotify/fsnotify 這東西也許是我們要找的

**Comment by PHChenGit** [comment]
請問方便描述這個 issue 想要即時更新使用者密碼是想解決什麼問題嗎？
或者說是想要達到什麼目的，所以要馬上更新使用者密碼？

**Comment by PichuChen** [comment]
這個部分應該可以算是 Ptt-Backend 那邊的 ISSUE 了。

他目前驗證密碼仰賴的是在啟動 Process 時呼叫 load userrecord 的函式讀入的資料，因此事後這個資料如果在硬碟上被修改了在現在版本的程式碼他並不會被同步更新這樣。

**Comment by PichuChen** [comment]
不過也許 userrrec 不應該讓 Ptt-Backend 那邊來管理，而是資料庫套件也就是 go-bbs 這邊要管理？

**Comment by PHChenGit** [comment]
> 這個部分應該可以算是 Ptt-Backend 那邊的 ISSUE 了。
> 
> 他目前驗證密碼仰賴的是在啟動 Process 時呼叫 load userrecord 的函式讀入的資料，因此事後這個資料如果在硬碟上被修改了在現在版本的程式碼他並不會被同步更新這樣。

我大概有拜讀一下程式碼，有了解到只有在登入的時候才會重新 load file
但是還是不確定為什麼想要改掉這個版本？
我的意思是 目前想要做到更改密碼後強迫所有平台都登出再重新登入 以確保使用者資料安全嗎？
或是要做到什麼事情這樣子？
如果沒有特別的原因是，只是覺得這樣比較合理的話，似乎可以把時間投資在其他功能（？

另外也許這個話題比較適合另開 issue 討論，但還是好奇想先問問看，目前市面上有許多開源好用的 DB 可以選擇
也許可以研究看看怎麼把這些 file 轉到 DB 後，後續好管理開發人員的生活也許就不需要這麼 hardcore？
