### ISSUE TITLE
[主線] [PTT] 實作 userinfo_t 解析

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/go-bbs#38]
**實作細節 / Details of Implement**
- 目前看起來需要解析在 pttstruct.h 裡面的 userinfo_t，測試資料從目前 shm 測試資料的 0x40510 位置開始，長度確認中。

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間： 一週
- 實作時間： 一週
- 確認時間：一週

**相關文件 / Documents**
https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/include/pttstruct.h#L349

**Comment by kyho4515** [comment]
hello, 我想幫忙這部分

**Comment by PichuChen** [comment]
麻煩你了❤️
