### ISSUE TITLE
UserRecord 介面缺少必要的方法

### ISSUE THREAD

**Issue by gn01842919** [Ptt-official-app/go-bbs#44]
**原本作法的問題 / Solved Problem**
- UserRecord 缺少部分的方法

**實作細節 / Details of Implement**
- 依據 PTT-Backend 的 API 文件，發現 UserRecord 缺少以下方法:
    - NumBadPosts()
    - LastCountry()
    - MailboxDescription()
    - ChessStatus()
    - Plan()

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間：一週
- 實作時間：一週
- 確認時間：一週

**Comment by PichuChen** [comment]
如果他的型別是
```golang
NumBadPosts() int
LastCountry() string
MailboxDescription() string
```

這樣的話不知道可不可以

另外 ChessStatus 應該是另外開一個 ChessUserRecord 來表示支援回傳棋盤狀態的使用者，裡面用 map 指到紀錄輸贏平手的資料結構。

然後 Plan 回傳一個 struct 裡面暫時先放還沒處理過的名片檔

**Comment by PichuChen** [comment]
@gn01842919 再幫忙看一下這樣行不行

**Comment by gn01842919** [comment]
LGTM
