### ISSUE TITLE
[建議] 支援 golang 1.16

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/go-bbs#45]
### 原本作法的問題 / Existed Problem
Golang 1.16 推出了，應該可以開一個 Branch 測試目前 1.16 跑起來會不會有問題

### 實作細節 / Details of Implement
建立一個 feature/golang_1_16 然後修改 CI 檔案讓他使用 golang 1.16 做測試，沒問題的話就 merge 回來

### 期程 / Schedule
- 討論時間：一日
- 實作時間：一日
- 確認時間：一日

### 相關文件 / Documents
https://golang.org/doc/go1.16

**Comment by minchao** [comment]
注意到目前 CI [go.yml](.github/workflows/go.yml) 中的 Go 版本設定是 `^1.13`

https://github.com/Ptt-official-app/go-bbs/blob/fe758895306cac39042f890d2449618b420c168c/.github/workflows/go.yml#L19

所以在執行時安裝的版本會是 1.x 最新版本，例如最近的 [Build #147](https://github.com/Ptt-official-app/go-bbs/runs/1935923458?check_suite_focus=true#step:2:10) 安裝的就是 `1.15.8`，估計過陣子執行的測試就會是安裝 `1.16` 了 😄

**Comment by minchao** [comment]
目前 CI 執行環境已經自動來到 `1.16`，請看：

https://github.com/Ptt-official-app/go-bbs/runs/2075158773?check_suite_focus=true#step:2:10

雖然這裡設定 `^1.13` 永遠會安裝最新的 `1.x` 版本，但隱含的是最低版本支援從 `1.13~1.x`，守備範圍就有點廣。不知到專案的 Go 版本支援策略為何？如果總是只支援最新版本的話，或許可以連著 go.mod 裡的版本宣告一起更新一下。

https://github.com/Ptt-official-app/go-bbs/blob/09df6eeef05320abf507fd38701889e7c71ccebe/go.mod#L3
