### ISSUE TITLE
缺少 PopularArticleRecord  介面

### ISSUE THREAD

**Issue by gn01842919** [Ptt-official-app/go-bbs#48]
**實作細節 / Details of Implement**
- 缺少 PopularArticleRecord 介面，應有以下 method:
    - `BoardId() string`

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間： 一週
- 實作時間： 一週
- 確認時間： 一週

**相關文件 / Documents**
[PTT後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.1ehnllv3ris)

**Comment by PichuChen** [comment]
這個未來應該會被改成 BoardID

**Comment by PichuChen** [comment]
熱門文章應該會由 Ptt-backend 來做統計和實作，因此先關掉這個 ISSUE 了
