### ISSUE TITLE
[主線] [PTT] 將 Id 改為 ID

### ISSUE THREAD

**Issue by y2468101216** [Ptt-official-app/go-bbs#52]
**實作細節 / Details of Implement**
目前有部分 code 使用 id 應該要改為 ID

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間：一天
- 實作時間： 三天
- 確認時間： 一天

**相關文件 / Documents**
使用 golint 確認

**Comment by titaneric** [comment]
這我可以幫忙，麻煩assign給我

**Comment by PichuChen** [comment]
@titaneric  感謝
