### ISSUE TITLE
[建議] 支援更好的命名及一致的coding style

### ISSUE THREAD

**Issue by titaneric** [Ptt-official-app/go-bbs#53]
**原本作法的問題 / Solved Problem**
- 目前在命名上有幾個golint會跳警告如下
  -  ALL_CAPS命名, Ex: `PTT_BRD_POSTMASK `
  - JSON, Ex: `favJson`
  - UI, Ex: `PosOfPttPasswdPagerUiType`
  - Error命名, Ex: `InvalidFavTypeError`
  - 不一致的receiver命名
  ```go
  // 前面用b
  func (b *BoardHeader) BoardID() string { return b.BrdName }
  // 後面用r
  func (r *BoardHeader) MarshalBinary() ([]byte, error)
   ```
- 一些語法可以更好
  - idx += 1 -> idx++
  - 移除unreachable code
 
**實作細節 / Details of Implement**
按照go lint建議改，這應該跟 #52 一樣問題。其中ALL_CAPS命名個人覺得有討論空間，畢竟原始的code是C

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間： 一週
- 實作時間： 一週
- 確認時間： 一週

**相關文件 / Documents**
Follow golint

另外是我已經開始著手更改了，麻煩assign給我，謝謝

**Comment by PichuChen** [comment]
ALL_CAPS 的問題我可以很確定應該要改掉他，然後 PosOf 的問題也是要被改掉

**Comment by PichuChen** [comment]
receiver 的命名有哪邊有文件介紹相關的規範嗎？ 因為我覺得他在同一個 name scope 底下的命名其實問題不大。

**Comment by titaneric** [comment]
應該是類似[golint下的測試](https://github.com/golang/lint/blob/master/testdata/receiver-names.go)
裡面有一個`// MATCH /receiver name a should be consistent with previous receiver name b for bar/`

**Comment by minchao** [comment]
@PichuChen 關於 Receiver Names 的命名，在官方 [CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#receiver-names) 文件裡提到：

> Be consistent, too: if you call the receiver "c" in one method, don't call it "cl" in another.

**Comment by titaneric** [comment]
這邊我覺得可以跟各位討論ALL_CAPS該怎麼改比較好，例如：`PTT_IDLEN`中間有縮寫命名的是改成`PttIdLen`嗎？會不會用`IdLen`就可以，因為我們有用module區分不同的bbs，PTT也許就可以省略。
另外我不太明白 @PichuChen 說的PosOf 的問題是指哪一個

**Comment by minchao** [comment]
以 `const PPT_IDLEN` 為例，參考官方文件：

`PTT` 部分，參考 [Package names](https://blog.golang.org/package-names)，使用 package 來組織程式碼，我們可以拿掉 `PPT` 前綴，避免 stutter：

> Avoid stutter. Since client code uses the package name as a prefix when referring to the package contents, the names for those contents need not repeat the package name. The HTTP server provided by the http package is called Server, not HTTPServer. Client code refers to this type as http.Server, so there is no ambiguity.

`ID` 部分，[CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#initialisms) 提到：

> This rule also applies to "ID" when it is short for "identifier" (which is pretty much all cases when it's not the "id" as in "ego", "superego"), so write "appID" instead of "appId".

`LEN` 部分，[Organizing Go Code (2014 Google I/O talk)](https://talks.golang.org/2014/organizeio.slide#21) 提到：

> Global variables should have longer names.

**Comment by PichuChen** [comment]
`PTT_IDLEN` 的問題我認為應該要被修改成 `IDLength` 或者是他應該要是一個 getter 假如這個值有可能被動態設定的話。 但是必須要有註解讓大家知道他要被參照到 [原本的地方](https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/include/pttstruct.h#L13)。

**Comment by minchao** [comment]
補充，Golint 處理的是 Coding style，所以有些規則可能見仁見智，雖然其文件提到 Google 正在內部使用，但爬一下 Go 原始碼也是可以發現許多反例 XD。且它是一個全有或全無的檢查器，無法忽略任一檢查規則。

**Comment by titaneric** [comment]
請問@PichuChen 指的是類似`PosOfFormosaBBSFileHeaderFilename`以及`PosOfPTTBoardName`這種有bbs各站的命名嗎？這在[pttbbs/README.md](https://github.com/Ptt-official-app/go-bbs/blob/development/pttbbs/README.md)有提到。

 另外golint看起來的確不打算支援ignore某些檢查(golang/lint#186)，可以的替代方案是有如[golangci-lint](https://github.com/golangci/golangci-lint)。但這些是非官方實作，若要放入CI/CD流程可以再開一個issue討論。

**Comment by PichuChen** [comment]
對，原本因為是在同個 package 所以用 PosOf 切開，但是現在已經分成不同套件了，所以不需要切開了。
