### ISSUE TITLE
[建議] 添加 golint 到 CI 流程中

### ISSUE THREAD

**Issue by minchao** [Ptt-official-app/go-bbs#57]
**原本作法的問題 / Solved Problem**
- 目前 #53 正在進行符合 [Golint](https://github.com/golang/lint) 檢查的修改，將自動檢查添加到 CI 流程中可避免未來發生違反規則的修改。

**實作細節 / Details of Implement**

目前有二方案，一是簡單添加  `golint` 工具直接執行。另一是使用 Go 生態圈常用的 Go linters aggregator [golangci-lint](https://golangci-lint.run/#features) 來執行 `golint`，額外的好處是，隨著專案持續發展，我們可以逐步啟用[各種靜態分析工具](https://golangci-lint.run/usage/linters/)。

**相關文件 / Documents**
- https://github.com/golang/lint
- https://github.com/golangci/golangci-lint

**Comment by RicoToothless** [comment]
我投 golangci-lint 一票
因為在 [GitHub Action](https://github.com/golangci/golangci-lint-action) 上做得比較完整而且也比較快（當然也要實際測一下）

我看 golint 沒什麼 GitHub Action，不然就要自己 `go get -u golang.org/x/lint/golint` 有點花 CI 時間。

**Comment by minchao** [comment]
補充，golangci-lint 預設排除 golint 中的 comment on exported 檢查，會比直接使用 golint 輕鬆許多。

see https://github.com/golangci/golangci-lint/blob/507703b444d95d8c89961bebeedfb22f61cde67c/pkg/config/config.go#L47-L59
