### ISSUE TITLE
[主線] [PTT] 實作個人看板歷史文章查詢 (repository)

### ISSUE THREAD

**Issue by whitefloor** [Ptt-official-app/go-bbs#59]
**實作細節 / Details of Implement**

* 查詢某User的歷史文章，主要是用來與ptt-backend對接repository使用
* cache依照ptt-backend ([#59](https://github.com/Ptt-official-app/Ptt-backend/issues/59)) 暫定不做，暫時是存放在go-bbs這
* 權限檢查參考其他的issue，一樣由ptt-backend處理

**期程 / Schedule**

* 此Issue與 https://github.com/Ptt-official-app/Ptt-backend/issues/59 連動，go-bbs處理完成後，ptt-backend就不需要mock
- 討論時間： 3/4-3/7(3 day)
- 實作時間： 3/8-3/11(3 day)
- 確認時間： 3/12/-3/15(3day)

**相關文件 / Documents**

* 其他參考文件請支援

**Comment by xboxa5105** [comment]
@PichuChen 
這個issue 關聯到https://github.com/Ptt-official-app/Ptt-backend/issues/59
再麻煩assign 給我 謝謝

**Comment by PichuChen** [comment]
> @PichuChen
> 這個issue 關聯到[Ptt-official-app/Ptt-backend#59](https://github.com/Ptt-official-app/Ptt-backend/issues/59)
> 再麻煩assign 給我 謝謝

@xboxa5105  再麻煩你了

**Comment by PichuChen** [comment]
@whitefloor  我可以確認一下這個 ISSUE 是針對 http 還是 usecase 還是 repository 的嗎？

**Comment by whitefloor** [comment]
@PichuChen 
是針對repository的

**Comment by PichuChen** [comment]
這邊看起來 go-bbs 應該是不用動才對？

**Comment by whitefloor** [comment]
需要實作go-bbs的Query
我是參照repository的這段程式碼去引用go-bbs的API
![image](https://user-images.githubusercontent.com/45685163/109962490-3799fd00-7d26-11eb-9ecf-08667b75a2b1.png)

**Comment by PichuChen** [comment]
現在應該是歷史文章查詢？所以應該不是使用 UserFavoriteRecords?

**Comment by PichuChen** [comment]
應該是用 https://pkg.go.dev/github.com/PichuChen/go-bbs#DB.ReadBoardArticleRecordsFile 這個做篩選？

**Comment by whitefloor** [comment]
應該說是引用他撰寫的方式，想說用userID就可以取得這個人過往的所有歷史文章
目前實作我是這樣
![image](https://user-images.githubusercontent.com/45685163/109963810-c9eed080-7d27-11eb-971f-945e8ccbe576.png)

如果用https://pkg.go.dev/github.com/PichuChen/go-bbs#DB.ReadBoardArticleRecordsFile 
應該是變成取得看板文章了

**Comment by PichuChen** [comment]
對，就是先取得看板文章，然後在 Ptt-backend 這邊判斷這篇文章屬不屬於某個使用者的，可能判斷過之後要再把判斷過的結果存下來？

**Comment by whitefloor** [comment]
好的，這樣我明白了，那這個issue再請你刪除，感謝
