### ISSUE TITLE
[主線] [PTT] 實作 BoardRecord interface 缺少的發文限制資訊

### ISSUE THREAD

**Issue by wagaru** [Ptt-official-app/go-bbs#61]
**實作細節 / Details of Implement**
BoardRecord 目前沒提供發文限制的相關資訊，所以需要提供以下 method：

* PostLimitPosts() uint8 // 發文次數
* PostLimitLogins() uint8 // 登入次數
* PostLimitBadPost() uint8 // 劣文次數

另外文件中的[發文限制] (https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#) 還有 regtime 註冊時間，如果最後需要也需一併加上
如果想要將資訊塞在新的 interface 的話也可以提出來討論~~

**期程 / Schedule**
- 討論時間： 一週
- 實作時間： 一週
- 確認時間：一週

**Comment by PichuChen** [comment]
預定的作法應該會在 bbs.go 裡面新增三個 interface 
第一個是 PostsLimitedBoardRecord 裡面實作 PostLimitPosts() uint8 
第二個是 LoginsLimitedBoardRecord 裡面實作 PostLimitLogins() uint8 
第三個是 BadPostLimitedBoardRecord 裡面實作 PostLimitBadPost() uint8

然後再到 pttbbs/board.go 去調整實作細節，不知道這樣如何？

**Comment by wagaru** [comment]
> 預定的作法應該會在 bbs.go 裡面新增三個 interface
> 第一個是 PostsLimitedBoardRecord 裡面實作 PostLimitPosts() uint8
> 第二個是 LoginsLimitedBoardRecord 裡面實作 PostLimitLogins() uint8
> 第三個是 BadPostLimitedBoardRecord 裡面實作 PostLimitBadPost() uint8

我本來是想說 ReadBoardRecords() 時一併將資訊回傳，所以才設計在 BoardRecord 裡。
如果這三個 Record 都只實作一個 function，
或許可以拆成一個 PostLimitedBoardRecord，然後裡面實作這三個 function 就好 ？

> 然後再到 pttbbs/board.go 去調整實作細節，不知道這樣如何？

那是會提供一個 public 函數一次回傳三個 Record，還是要分別呼叫取得個自的 Record ？

**Comment by PichuChen** [comment]
> > 預定的作法應該會在 bbs.go 裡面新增三個 interface
> > 第一個是 PostsLimitedBoardRecord 裡面實作 PostLimitPosts() uint8
> > 第二個是 LoginsLimitedBoardRecord 裡面實作 PostLimitLogins() uint8
> > 第三個是 BadPostLimitedBoardRecord 裡面實作 PostLimitBadPost() uint8
> 
> 我本來是想說 ReadBoardRecords() 時一併將資訊回傳，所以才設計在 BoardRecord 裡。
> 如果這三個 Record 都只實作一個 function，
> 或許可以拆成一個 PostLimitedBoardRecord，然後裡面實作這三個 function 就好 ？
> 
> > 然後再到 pttbbs/board.go 去調整實作細節，不知道這樣如何？
> 
> 那是會提供一個 public 函數一次回傳三個 Record，還是要分別呼叫取得個自的 Record ？

會想要分三個的原因是因為這三個實作並不是一個 BBS 系統的最基本必須，他算是選用性的功能這樣
