### ISSUE TITLE
[主線] [PTT] 取得使用者設定

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/go-bbs#78]
**實作細節 / Details of Implement**
- 請見 [userec_t](https://github.com/ptt/pttbbs/blob/5715b35f510f48eb5092d32882f1aa09181dc3a1/include/pttstruct.h#L57) 中的 uflag 和 userlevel
- 每個選項對應的 flag id 請參見 [user.c](https://github.com/ptt/pttbbs/blob/5715b35f510f48eb5092d32882f1aa09181dc3a1/mbbsd/user.c#L438)  desc1 和 masks1

<img width="972" alt="截圖 2021-04-18 下午2 03 38" src="https://user-images.githubusercontent.com/600238/115135983-4119c300-a04f-11eb-873f-53642cc710be.png">

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間： 一天 4/19
- 實作時間： 一週 4/25
- 確認時間： 一週 5/2

**相關文件 / Documents**
[userec_t](https://github.com/ptt/pttbbs/blob/5715b35f510f48eb5092d32882f1aa09181dc3a1/include/pttstruct.h#L57)

**Comment by AmberFu** [comment]
我會試試實作這部分。

**Comment by PichuChen** [comment]
> 我會試試實作這部分。

Hello, 目前還 OK 嗎？

**Comment by AmberFu** [comment]
> > 我會試試實作這部分。
> 
> Hello, 目前還 OK 嗎？

目前正在實作，可能需要多一些時間，不好意思。

**Comment by PichuChen** [comment]
@AmberFu 想問一下目前大致上到哪邊了？

**Comment by AmberFu** [comment]
> @AmberFu 想問一下目前大致上到哪邊了？

目前在實作幾個 method，傳入 userid 然後回傳該使用者的BBS 設定，預計本週可以完成
