### ISSUE TITLE
[主線] [PTT] 實作看板發文限制以及細部資訊

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/go-bbs#79]
**實作細節 / Details of Implement**
- [board.c](https://github.com/ptt/pttbbs/blob/5715b35f510f48eb5092d32882f1aa09181dc3a1/mbbsd/board.c#L338) 檔案的 b_config 上面有看板限制和細部資訊，兩邊基本上是一起被取出的，所以可以放在同個 Method 出來。

<img width="976" alt="截圖 2021-04-18 下午3 07 59" src="https://user-images.githubusercontent.com/600238/115137279-df118b80-a057-11eb-8ded-e1d964caf57d.png">

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間： 一天 4/19
- 實作時間： 一週 4/26
- 確認時間： 一週 5/3

**相關文件 / Documents**

**Comment by nickyanggg** [comment]
我可以試試這個～

**Comment by PichuChen** [comment]
Ok, 再麻煩你了
