### ISSUE TITLE
[主線] [PTT] 實作在文章底部新增一行文字的method

### ISSUE THREAD

**Issue by PichuChen** [Ptt-official-app/go-bbs#82]
**實作細節 / Details of Implement**
- 目前在 [實作文章推文](https://github.com/Ptt-official-app/Ptt-backend/issues/194) 以及 [轉錄看板文章](https://github.com/Ptt-official-app/Ptt-backend/issues/66) 都需要直接新增一行字串
- 直接編輯整個文章和在後面新增一行字串在硬碟上的效率不太一樣，新增字串會有比較高的效能
- 可能會在原有文章或是 bbs 的 connecter 新增一個 method 裡面有參數來表示某個看板的某個文章，然後和一行任意文字。
- 請參考 bbs.c 的 do_add_recommend

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間： 三天，5/2
- 實作時間： 一週，5/9
- 確認時間： 一週，5/16

**相關文件 / Documents**

轉錄文章在 bbs.c 的 cross_post

基本上是為了實作這樣的功能
<img width="990" alt="截圖 2021-04-30 上午12 24 12" src="https://user-images.githubusercontent.com/600238/116584922-71fcd080-a94a-11eb-9e6b-7eb0c068e71b.png">

**Comment by ChihSeanHsu** [comment]
這issue有人接嗎？沒有的話可以幫忙。

**Comment by PichuChen** [comment]
目前這個可能要同時等 ~~cross_post~~ do_add_recomment 的函式註解完成 https://docs.google.com/spreadsheets/d/1ITDYuj6TjeodZDtnXPrctZ6We6Mz_tXosmR_O1TCkXo/edit#gid=0

這部分可能要聯絡 ~~https://github.com/wagaru~~ dogeTW 協調喔

**Comment by PichuChen** [comment]
誒不對，好像是 do_add_recomment ，這個 doge 那邊還沒有回應，所以你如果要做的話可以先在 Google Sheet 上面提示一下你那邊會接手

**Comment by ChihSeanHsu** [comment]
好的，有兩個問題想要問一下，

1.  這個method(暫稱`AppendNewLine`)會讓`do_add_recomment`跟`cross_post`共用?
2.  `do_add_recomment` 有開相關的issue或PR嗎?

感謝

**Comment by PichuChen** [comment]
> 好的，有兩個問題想要問一下，
> 
> 1. 這個method(暫稱`AppendNewLine`)會讓`do_add_recomment`跟`cross_post`共用?
> 2. `do_add_recomment` 有開相關的issue或PR嗎?
> 
> 感謝

這個method不會使用到 do_add_recomment 或是被 do_add_recomment 使用，他會像是實作 Golang 版本的 do_add_Recomment (原版是C語言的版本)

**Comment by ChihSeanHsu** [comment]
> 
> 
> > 好的，有兩個問題想要問一下，
> > 
> > 1. 這個method(暫稱`AppendNewLine`)會讓`do_add_recomment`跟`cross_post`共用?
> > 2. `do_add_recomment` 有開相關的issue或PR嗎?
> > 
> > 感謝
> 
> 這個method不會使用到 do_add_recomment 或是被 do_add_recomment 使用，他會像是實作 Golang 版本的 do_add_Recomment (原版是C語言的版本)

了解了，剛剛稍微去看了一下bbs.c，
感謝你的回應。

**Comment by ChihSeanHsu** [comment]
Hi @PichuChen ,

目前已經在google sheet裡填入`do_add_recommend`的註解了。

準備開始實作，但可能這個issue會跟[#83](https://github.com/Ptt-official-app/go-bbs/issues/83)有些相依，需要使用到那邊的connector，
或是這個會是個獨立的connector?

**Comment by PichuChen** [comment]
@ChihSeanHsu 他應該可以是個獨立的 Connector, 或是兩邊誰後近來在處理merge即可

**Comment by PichuChen** [comment]
@ChihSeanHsu  我發現你那邊目前實作的函式不夠一般化，他有點太針對**推文**了，我原先的想法是如果可以新增一個函式，他是可以自定義內容的，那這樣轉發文章的系統訊息就可以用這個函式來完成了。

而接著在使用者推文的部分則是呼叫這個函式進行就行了。
不知道你覺得這個想法如何？

**Comment by ChihSeanHsu** [comment]
Hi @PichuChen,
我覺得有可能是function命名的問題，因為目前是照著原本的bbs.c做些變動搬過來的，我一直覺得名字有點不太合適。

因為從bbs.c裡面看起來是轉發文章跟推文都是在最後呼叫這個`do_add_recommend`，
所以從那個角度來看，轉發文章的系統資訊也算是一種推文。

但如果說要更加一般化的話，我認為是可以把那些recommend的數目跟還有已讀重算這些拔出來，等到實作推文的時候再去實作他們，這個function單純就是處理增加一行文字到檔案的最底部就好。

也就是只傳入`direct, fileHeader, buf`這三個東西。

**Comment by PichuChen** [comment]
@ChihSeanHsu 我覺得把算數目（或是說設定數目）和文章內容修改切開很ＯＫ
