### ISSUE TITLE
[主線] [PTT] 實作發表文章

### ISSUE THREAD

**Issue by wagaru** [Ptt-official-app/go-bbs#83]
**實作細節 / Details of Implement**
- 在 [bbs.go](https://github.com/Ptt-official-app/go-bbs/blob/development/bbs.go) 新增 WriteArticleConnector interface，此 interface 要實作以下二個函式
    - NewArticleRecord(args map[string]interface{}) (ArticleRecord, error)
    - AddArticleRecordFileRecord(name string, article ArticleRecord) error
- 在 pttbbs 套件新增 pttbbs_write_article_connector.go
  - NewArticleRecord(args map[string]interface{}) (ArticleRecord, error)
    - 產生並建立 fileName，對應到 [setbpath](https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/mbbsd/syspost.c#L13) 與 [stampfile](https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/mbbsd/syspost.c#L14)，命名規則可參考 stampfile 的 [底層函式](https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/common/bbs/fhdr_stamp.c#L49) ，並要確保檔名唯一性
    - 寫入文章內容，要一併寫入作者、看板、標題、時間。參考 [syspost.c](https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/mbbsd/syspost.c#L23)
    - 回傳 FileHeader struct，需設定 fileName、date、title、owner
  - AddArticleRecordFileRecord(name string, article ArticleRecord) error
    - 將 FileHeader 寫入 name 指定的路徑，注意要加上 file lock，參考[append_record](https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/common/sys/record.c#L93)

待確認：[setbtotal](https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/mbbsd/syspost.c#L35) 要在哪邊呼叫
  
**期程 / Schedule**
- 討論時間： [e.g. 一週, 到 5/12]
- 實作時間： [e.g. 一週, 到 5/19]
- 確認時間： [e.g. 一週, 到 5/26]

**相關文件 / Documents**
[pttbbs 函式註解](https://docs.google.com/spreadsheets/d/1ITDYuj6TjeodZDtnXPrctZ6We6Mz_tXosmR_O1TCkXo/edit#gid=0)

**Comment by nickyanggg** [comment]
我可以試試這個～
