### ISSUE TITLE
[主線] [PTT] 實作 erase_tmpbuf

### ISSUE THREAD

**Issue by gogog22510** [Ptt-official-app/go-bbs#89]
**實作細節 / Details of Implement**
* 實作移除文章草稿的功能
* 請參考 [edit.c](https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/mbbsd/edit.c) 下的 `erase_tmpbuf(void)`

**期程 / Schedule**
- 討論時間： 一週, 到 6/7
- 實作時間： 一週, 到 6/14
- 確認時間： 一週, 到 6/21

**相關文件 / Documents**
請參考[函式註解](https://docs.google.com/spreadsheets/d/1ITDYuj6TjeodZDtnXPrctZ6We6Mz_tXosmR_O1TCkXo/edit?usp=sharing)

這個功能是為了實作以下功能
![image](https://user-images.githubusercontent.com/7885614/120232996-c681bd00-c222-11eb-9d05-04d2bca97f93.png)
![image](https://user-images.githubusercontent.com/7885614/120233033-d6010600-c222-11eb-9f3c-f98d6e53d3e3.png)

**Comment by nickyanggg** [comment]
我可以幫忙
