### ISSUE TITLE
[主線] [PTT] 實作 read_tmpbuf 

### ISSUE THREAD

**Issue by gogog22510** [Ptt-official-app/go-bbs#91]
**實作細節 / Details of Implement**
* 實作讀取草稿的功能
* 原始碼參考[edit.c 的 read_tmpbuf](https://github.com/ptt/pttbbs/blob/4d56e77f264960e43e060b77e442e166e5706417/mbbsd/edit.c#L1283)
* 參考 #89 的Pull Request
* 在 bbs.go 和 draft.go 裡加入 ReadUserDraft method (具體參數和實作細節請參考註解和原始碼)
* 可以的話加入test case

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間： 一週, 到 6/11
- 實作時間： 一週, 到 6/18
- 確認時間： 一週, 到 6/25

**相關文件 / Documents**
參考[method 註解](https://docs.google.com/spreadsheets/d/1ITDYuj6TjeodZDtnXPrctZ6We6Mz_tXosmR_O1TCkXo/edit?usp=sharing)

**Comment by nickyanggg** [comment]
我可以試試
