### ISSUE TITLE
[主線] [PTT] 實作 write_tmpbuf

### ISSUE THREAD

**Issue by RicoToothless** [Ptt-official-app/go-bbs#92]
**實作細節 / Details of Implement**
- 實作當使用者 bbs 編輯器要寫入暫存檔的功能，以下是觸發此功能的流程：
    - 寫文章或寄信時選擇 (^X) 後進入檔案處理 [edit.c write_file](https://github.com/ptt/pttbbs/blob/master/mbbsd/edit.c#L1924)
    - 使用者在「確定要儲存檔案嗎？」選擇 (w) 後進入 `write_tmpbuf` 函式
- 功能解說請參考 [google sheet pttbbs write_tmpbuf 函式註解](https://docs.google.com/spreadsheets/d/1ITDYuj6TjeodZDtnXPrctZ6We6Mz_tXosmR_O1TCkXo/edit#gid=0&range=A27)
- 原始碼參考請 [edit.c 的 write_tmpbuf(void)](https://github.com/ptt/pttbbs/blob/master/mbbsd/edit.c#L1315)
- 可以的話加入 test case

**期程 / Schedule**
(希望這個任務大概什麼時候做完，如果會卡到其他地方的功能也請在這邊提出。)
- 討論時間： [e.g. 一週, 到 7/11]
- 實作時間： [e.g. 一週, 到 7/18]
- 確認時間： [e.g. 一週, 到 7/25]

**相關文件 / Documents**
- [google sheet pttbbs write_tmpbuf 函式註解](https://docs.google.com/spreadsheets/d/1ITDYuj6TjeodZDtnXPrctZ6We6Mz_tXosmR_O1TCkXo/edit#gid=0&range=A27)
- [原始碼 edit.c 的 write_tmpbuf(void)](https://github.com/ptt/pttbbs/blob/master/mbbsd/edit.c#L1315)

**參考流程圖片**

![image](https://user-images.githubusercontent.com/39393540/120882266-0f61b900-c609-11eb-868f-f148257c083f.png)

<img width="955" alt="Screen Shot 2021-06-05 at 2 16 36 PM" src="https://user-images.githubusercontent.com/39393540/120882238-df1a1a80-c608-11eb-9210-85d8bd096e8b.png">

**Comment by cftang0827** [comment]
我可以試試看！

**Comment by PichuChen** [comment]
@cftang0827  交給你了

**Comment by cftang0827** [comment]
初步的看了一下code 想請教一下有關於流程的問題
所以基本上這個function的任務是只有按下”w”以後直接檔案覆寫的行為對嗎？這邊不用去管這個draft id  檔案是否已經有內容？

謝謝🙏

**Comment by PichuChen** [comment]
我認為不用管，這部分應該由上層來檢查
