### ISSUE TITLE
[建議] 修改 UserCommentRecord 

### ISSUE THREAD

**Issue by nickyanggg** [Ptt-official-app/go-bbs#95]
**原本作法的問題 / Solved Problem**
目前 bbs.UserCommentRecord 只提供下列方法，然而 Ptt-backend 那邊在使用時仍需該 comment 所屬 bbs.ArticleRecord 的[資訊](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.xtgbc6lc04uw)(如下圖)
```golang
type UserCommentRecord interface {
	CommentOrder() uint32
	CommentOwner() string
	CommentTime() time.Time
	String() string
}
```
![截圖 2021-06-21 上午8 20 28](https://user-images.githubusercontent.com/38569272/123134710-a80a8c80-d483-11eb-870d-50f66e2472d1.png)

**實作細節 / Details of Implement**

新增 BoardID()、Filename() 等 method
```golang
type UserCommentRecord interface {
	CommentOrder() uint32
	CommentTime() time.Time
        Owner() string
        IP() string
	String() string
	BoardID() string
        Filename() string
}
```

**期程 / Schedule**
- 討論時間： 一週
- 實作時間：如果大家覺得沒問題的話這邊我可以開始實作

**相關文件 / Documents**
[API 文件](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.xtgbc6lc04uw)

**Comment by PichuChen** [comment]
可以考慮加上IP?

**Comment by nickyanggg** [comment]
> 可以考慮加上IP?

好

**Comment by PichuChen** [comment]
@nickyanggg  這個ISSUE怎麼了嗎？

**Comment by nickyanggg** [comment]
> @nickyanggg 這個ISSUE怎麼了嗎？

之前以為不用修改所以就先把這支 issue 以及對應到的 pr 關掉了，後來討論結果是先儲存 boardname、filename 即可
